[versions]
androidDocumentationPlugin = "2.1.0"
compileSdk = "36"
kotlinxCoroutinesCore = "1.10.2"
kotlinxSerializationJson = "1.9.0"
minSdk = "24"
mockk = "1.14.6"
moshiKotlinCodegen = "1.15.2"
targetSdk = "36"
jvmTarget = "21"
sourceCompatibility = "VERSION_21"
targetCompatibility = "VERSION_21"

lifecycle = "2.10.0"
retrofit = "3.0.0"
composeBom = "2025.11.01"

detekt = "1.23.8"

androidGradlePlugin = "8.13.1"
kotlin = "2.2.21"
ksp = "2.2.21-2.0.4"
kotestRunnerJunit5Jvm = "6.0.5"

[libraries]

android-documentation-plugin = { module = "org.jetbrains.dokka:android-documentation-plugin", version.ref = "androidDocumentationPlugin" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }

architectural-rules = { module = "shaha.gaurang:architectural-rules", version = "1.0.0" }
foundation = { module = "building.blocks:foundation", version = "1.0.0" }
crypto = { module = "building.blocks:crypto", version = "1.0.0" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.12.0" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

coil = { group = "io.coil-kt", name = "coil-compose", version = "2.7.0" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlinCodegen" }
ratingbar = { group = "com.github.a914-gowtham", name = "compose-ratingbar", version = "1.3.4" }
window-size = { group = "androidx.compose.material3", name = "material3-window-size-class", version = "1.4.0" }

koin = { group = "io.insert-koin", name = "koin-androidx-compose", version = "4.1.1" }

navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.6" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "5.3.2" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-appkode-compose = { group = "ru.kode", name = "detekt-rules-compose", version = "1.4.0" }
detekt-twitter-compose = { group = "com.twitter.compose.rules", name = "detekt", version = "0.0.26" }
kotest-runner-junit5-jvm = { group = "io.kotest", name = "kotest-runner-junit5-jvm", version.ref = "kotestRunnerJunit5Jvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
